# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adding.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Add_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setStyleSheet("background-color: #ededed;")
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setGeometry(QtCore.QRect(320, 260, 61, 30))
        self.okButton.setStyleSheet("background-color: #ededed; border: 1px solid grey;\n"
"     border-radius: 15px;\n"
"font: \"Segoe UI\";\n"
"color: #707070")
        self.okButton.setObjectName("okButton")
        self.siteEdit = QtWidgets.QLineEdit(Dialog)
        self.siteEdit.setGeometry(QtCore.QRect(220, 30, 150, 30))
        self.siteEdit.setStyleSheet("background-color: #ededed; border: 1px solid grey;\n"
"     border-radius: 15px;\n"
"font: \"Segoe UI\";\n"
"color: #707070")
        self.siteEdit.setObjectName("siteEdit")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 40, 47, 20))
        self.label.setObjectName("label")
        self.mailEdit = QtWidgets.QLineEdit(Dialog)
        self.mailEdit.setGeometry(QtCore.QRect(220, 90, 150, 30))
        self.mailEdit.setStyleSheet("background-color: #ededed; border: 1px solid grey;\n"
"     border-radius: 15px;\n"
"font:  \"Segoe UI\";\n"
"color: #707070")
        self.mailEdit.setObjectName("mailEdit")
        self.passwordEdit = QtWidgets.QLineEdit(Dialog)
        self.passwordEdit.setGeometry(QtCore.QRect(220, 150, 150, 30))
        self.passwordEdit.setStyleSheet("background-color: #ededed; border: 1px solid grey;\n"
"     border-radius: 15px;\n"
"font: \"Segoe UI\";\n"
"color: #707070")
        self.passwordEdit.setObjectName("passwordEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 81, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 160, 51, 20))
        self.label_3.setObjectName("label_3")
        self.hideButton = QtWidgets.QPushButton(Dialog)
        self.hideButton.setGeometry(QtCore.QRect(230, 260, 61, 30))
        self.hideButton.setStyleSheet("background-color: #ededed; border: 1px solid grey;\n"
"     border-radius: 15px;\n"
"font: \"Segoe UI\";\n"
"color: #707070")
        self.hideButton.setObjectName("hideButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.okButton.setText(_translate("Dialog", "OK"))
        self.label.setText(_translate("Dialog", "Site:"))
        self.label_2.setText(_translate("Dialog", "Mail or Loggin:"))
        self.label_3.setText(_translate("Dialog", "Password:"))
        self.hideButton.setText(_translate("Dialog", "Cancel"))
