# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delete.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 312)
        Dialog.setStyleSheet("background-color: #ededed; border: 1px solid grey;\n"
"     border-radius: 15px;\n"
"font: \"Segoe UI\";\n"
"color: #707070")
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setGeometry(QtCore.QRect(320, 270, 61, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okButton.sizePolicy().hasHeightForWidth())
        self.okButton.setSizePolicy(sizePolicy)
        self.okButton.setStyleSheet("background-color: #ededed; border: 1px solid grey;\n"
"     border-radius: 15px;\n"
"font: \"Segoe UI\";\n"
"color: #707070")
        self.okButton.setObjectName("okButton")
        self.siteEdit = QtWidgets.QLineEdit(Dialog)
        self.siteEdit.setGeometry(QtCore.QRect(210, 130, 150, 30))
        self.siteEdit.setStyleSheet("background-color: #ededed; border: 1px solid grey;\n"
"     border-radius: 15px;\n"
"font: \"Segoe UI\";\n"
"color: #707070")
        self.siteEdit.setObjectName("siteEdit")
        self.hideButton = QtWidgets.QPushButton(Dialog)
        self.hideButton.setGeometry(QtCore.QRect(230, 270, 61, 30))
        self.hideButton.setStyleSheet("background-color: #ededed; border: 1px solid grey;\n"
"     border-radius: 15px;\n"
"font: \"Segoe UI\";\n"
"color: #707070")
        self.hideButton.setObjectName("hideButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 130, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.okButton.setText(_translate("Dialog", "OK"))
        self.hideButton.setText(_translate("Dialog", "Cancel"))
        self.label.setText(_translate("Dialog", "id of row:"))
