# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(1280, 720))
        Form.setMaximumSize(QtCore.QSize(1280, 720))
        Form.setStyleSheet("background-color: rgb(237, 237, 237);")
        self.logButton = QtWidgets.QPushButton(Form)
        self.logButton.setGeometry(QtCore.QRect(630, 464, 300, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.logButton.setFont(font)
        self.logButton.setAutoFillBackground(False)
        self.logButton.setStyleSheet("background-color: #ededed; border: 1px solid grey;\n"
"     border-radius: 35px;\n"
"font: 40pt \"Segoe UI\";\n"
"color: #707070")
        self.logButton.setObjectName("logButton")
        self.passwordEdit = QtWidgets.QLineEdit(Form)
        self.passwordEdit.setGeometry(QtCore.QRect(628, 321, 300, 70))
        self.passwordEdit.setStyleSheet("background-color: #ededed; border: 1px solid grey;\n"
"     border-radius: 35px;\n"
"font: 40pt \"Segoe UI\";\n"
"color: #707070")
        self.passwordEdit.setObjectName("passwordEdit")
        self.loginEdit = QtWidgets.QLineEdit(Form)
        self.loginEdit.setGeometry(QtCore.QRect(628, 186, 300, 70))
        self.loginEdit.setStyleSheet("background-color: #ededed; border: 1px solid grey;\n"
"     border-radius: 35px;\n"
"font: 40pt \"Segoe UI\";\n"
"color: #707070")
        self.loginEdit.setObjectName("loginEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(387, 180, 141, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 40pt \"Segoe UI\";\n"
"color: #707070")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(353, 320, 231, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 40pt \"Segoe UI\";\n"
"color: #707070")
        self.label_2.setObjectName("label_2")
        self.cancelButton = QtWidgets.QPushButton(Form)
        self.cancelButton.setGeometry(QtCore.QRect(310, 464, 300, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(35)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.cancelButton.setFont(font)
        self.cancelButton.setAutoFillBackground(False)
        self.cancelButton.setStyleSheet("background-color: #ededed; border: 1px solid grey;\n"
"     border-radius: 35px;\n"
"font: 35pt \"Segoe UI\";\n"
"color: #707070")
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.logButton.setText(_translate("Form", "Login"))
        self.label.setText(_translate("Form", "Login:"))
        self.label_2.setText(_translate("Form", "Password:"))
        self.cancelButton.setText(_translate("Form", "Go to register"))
