# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Search_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 312)
        Dialog.setStyleSheet("background-color: #ededed; border: 1px solid grey;\n"
"     border-radius: 15px;\n"
"font: \"Segoe UI\";\n"
"color: #707070")
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setGeometry(QtCore.QRect(320, 270, 61, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okButton.sizePolicy().hasHeightForWidth())
        self.okButton.setSizePolicy(sizePolicy)
        self.okButton.setStyleSheet("background-color: #ededed; border: 1px solid grey;\n"
"     border-radius: 15px;\n"
"font: \"Segoe UI\";\n"
"color: #707070")
        self.okButton.setObjectName("okButton")
        self.siteEdit = QtWidgets.QLineEdit(Dialog)
        self.siteEdit.setGeometry(QtCore.QRect(230, 60, 150, 30))
        self.siteEdit.setStyleSheet("background-color: #ededed; border: 1px solid grey;\n"
"     border-radius: 15px;\n"
"font: \"Segoe UI\";\n"
"color: #707070")
        self.siteEdit.setObjectName("siteEdit")
        self.hideButton = QtWidgets.QPushButton(Dialog)
        self.hideButton.setGeometry(QtCore.QRect(230, 270, 61, 30))
        self.hideButton.setStyleSheet("background-color: #ededed; border: 1px solid grey;\n"
"     border-radius: 15px;\n"
"font: \"Segoe UI\";\n"
"color: #707070")
        self.hideButton.setObjectName("hideButton")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(20, 60, 150, 30))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(15, 110, 371, 151))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.okButton.setText(_translate("Dialog", "OK"))
        self.hideButton.setText(_translate("Dialog", "Cancel"))
        self.comboBox.setItemText(0, _translate("Dialog", "Site"))
        self.comboBox.setItemText(1, _translate("Dialog", "Mail or Login"))
        self.comboBox.setItemText(2, _translate("Dialog", "Password"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Site"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Password"))
