# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Storage.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(1280, 720))
        Form.setMaximumSize(QtCore.QSize(1280, 720))
        Form.setStyleSheet("background-color: rgb(237, 237, 237);")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1271, 721))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.tableWidget.setStyleSheet("background-color: rgb(237, 237, 237);\n"
"font: 10pt \"Segoe UI\";\n"
"color: #707070")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.addButton.setStyleSheet("background-color: #ededed; border: 1px solid grey;\n"
"     border-radius: 5px;\n"
"font: 8pt \"Segoe UI\";\n"
"color: #707070")
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.deleteButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.deleteButton.setStyleSheet("background-color: #ededed; border: 1px solid grey;\n"
"     border-radius: 5px;\n"
"font: 8pt \"Segoe UI\";\n"
"color: #707070")
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout.addWidget(self.deleteButton)
        self.searchButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.searchButton.setStyleSheet("background-color: #ededed; border: 1px solid grey;\n"
"     border-radius: 5px;\n"
"font: 8pt \"Segoe UI\";\n"
"color: #707070")
        self.searchButton.setObjectName("searchButton")
        self.horizontalLayout.addWidget(self.searchButton)
        self.showButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.showButton.setStyleSheet("background-color: #ededed; border: 1px solid grey;\n"
"     border-radius: 5px;\n"
"font: 8pt \"Segoe UI\";\n"
"color: #707070")
        self.showButton.setObjectName("showButton")
        self.horizontalLayout.addWidget(self.showButton)
        self.logButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.logButton.setStyleSheet("background-color: #ededed; border: 1px solid grey;\n"
"     border-radius: 5px;\n"
"font: 8pt \"Segoe UI\";\n"
"color: #707070")
        self.logButton.setObjectName("logButton")
        self.horizontalLayout.addWidget(self.logButton)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Site"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Mail or Login"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Password"))
        self.addButton.setText(_translate("Form", "Add"))
        self.deleteButton.setText(_translate("Form", "Delete"))
        self.searchButton.setText(_translate("Form", "Search"))
        self.showButton.setText(_translate("Form", "Show Passwords"))
        self.logButton.setText(_translate("Form", "Log Out"))
